export enum USER_EVENTS {
  UPDATE_SESSION = "UPDATE_SESSION",
  LOGOUT = "LOGOUT",
  FETCH_MODULES = "FETCH_MODULES",
  LOGIN = "LOGIN",
  IS_LOGGED_IN = "IS_LOGGED_IN",
  GET_ONLINE_USERS = "GET_ONLINE_USERS",
  ONLINE_USERS = "ONLINE_USERS",
}
