export enum USER_EVENTS {
  UPDATE_SESSION = "UPDATE_SESSION",
  LOGOUT = "USER_LOGOUT",
  LOGIN = "USER_LOGIN",
  SESSION = "USER_SESSION",
  FETCH_MODULES = "FETCH_MODULES",
  IS_LOGGED_IN = "IS_LOGGED_IN",
  GET_ONLINE_USERS = "GET_ONLINE_USERS",
  ONLINE_USERS = "ONLINE_USERS",
  LOG_USER_OUT = "LOG_USER_OUT",
  REFETCH_USERS = "REFETCH_USERS",
}
